DELIMITER $$

CREATE PROCEDURE CONTACTLIST(IN USR VARCHAR(300))
BEGIN
	CREATE TEMPORARY TABLE RES(USERNAME VARCHAR(300), FIRST_NAME VARCHAR(100), LAST_NAME VARCHAR(100), STATUS BOOLEAN, LAST_ONLINE DATETIME, BLOCKED BOOLEAN DEFAULT FALSE);
INSERT INTO RES(USERNAME, FIRST_NAME, LAST_NAME, STATUS, LAST_ONLINE) (SELECT USERNAME, FIRST_NAME, LAST_NAME, STATUS, LAST_ONLINE FROM USERS WHERE USERNAME NOT IN (SELECT USERNAME1 FROM BLOCKED_LIST WHERE USERNAME2 = USR) AND USERNAME != USR);
UPDATE RES SET BLOCKED = TRUE WHERE USERNAME IN (SELECT USERNAME2 FROM BLOCKED_LIST WHERE USERNAME1 = USR);
SELECT * FROM RES;
DROP TABLE RES;
END $$

DELIMITER ;

DELIMITER $$

CREATE PROCEDURE REGISTER(IN USR VARCHAR(300), IN PASS VARCHAR(50), IN FIRSTNAME VARCHAR(100), IN LASTNAME VARCHAR(100))
BEGIN
INSERT INTO USERS VALUES(USR, PASS, FIRSTNAME, LASTNAME, TRUE, NULL);
END $$

DELIMITER ;

DELIMITER $$

